spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/todo
    username:
      root
    password:
      123
    driver:
      class:
        com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    databese: mysql
    database-plataform: org.hibernate.dialect.MySQL8InnoDBDialect


env:
  secret_key: "45774a4a9b3ab452ea91681d20a1ace04168ebde939d88e7ee647eeacf9d487a"


